#ping-test.yml, I use this as a test playbook when working at CHIC in 2025 using AAP
- name: Test de connectivité
  hosts: all
  gather_facts: no
  tasks:
    - name: Ping
      ansible.builtin.ping:
      ignore_errors: yes

